name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Yandex Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YANDEX_CLOUD_KEY }}

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/crph8la4elkq8clar20b/iketel-frontend:latest .
          
      - name: Push Docker image to Yandex Container Registry
        run: |
          docker push cr.yandex/crph8la4elkq8clar20b/iketel-frontend:latest

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > server_key.pem
          chmod 600 server_key.pem

      - name: Copy to server
        uses: appleboy/scp-action@v1
        with:
          host: ${secrets.SERVER_IP}
          username: ${secrets.SERVER_USERNAME}
          key: ${secrets.SERVER_SSH_KEY}
          target: /var/www/frontend/
          
        







